## with this we are deploying both service and deployment in one file
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: newapp
  template:
    metadata:
      name: mypod
      labels:
        app: newapp
    spec:
      containers:
        - name: newapp
          image: httpd
          ports:
          - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: load
spec:
  type: LoadBalancer
  selector:
    app: newapp
  ports:
    - protocol: TCP
      port: 80

